WITH PRODUTOS AS (
    SELECT CODI_PSV FROM PRODUTO WHERE CODI_TRA = 10006412
)
SELECT
    1 AS EMPRESA,
    P.CORI_PRO AS CODIGO_ORIGINAL,
    PD.DESC_PSV AS DESCRICAO,
    COALESCE((SELECT SUM(SALD_CTR) AS SALDO FROM TABLE (SALDO_INICIAL_TIPOEST(1, 2, PD.CODI_PSV, SYSDATE, 'S', NULL, NULL))), 0) AS ESTOQUE
FROM PRODSERV PD
LEFT JOIN PRODUTO P ON (P.CODI_PSV = PD.CODI_PSV)
WHERE PD.CODI_PSV IN (SELECT CODI_PSV FROM PRODUTOS)

UNION ALL

SELECT
    5 AS EMPRESA,
    P.CORI_PRO AS CODIGO_ORIGINAL,
    PD.DESC_PSV AS DESCRICAO,
    COALESCE((SELECT SUM(SALD_CTR) AS SALDO FROM TABLE (SALDO_INICIAL_TIPOEST(5, 2, PD.CODI_PSV, SYSDATE, 'S', NULL, NULL))), 0) AS ESTOQUE
FROM PRODSERV PD
LEFT JOIN PRODUTO P ON (P.CODI_PSV = PD.CODI_PSV)
WHERE PD.CODI_PSV IN (SELECT CODI_PSV FROM PRODUTOS);

