SELECT 

NF.CODI_EMP AS CODIGO_EMPRESA,
NF.NUME_NFE AS NUMERO_NOTA,
NF.SERI_NFE AS SERIE_NOTA,
NF.DREC_NFE AS DATA_RECEBIMENTO,
INF.CODI_PSV AS CODIGO_PRODUTO,
P.DESC_PSV AS DESCRICAO,
INF.VLOR_INF AS PRECO_UNITARIO,
INF.QUAN_INF AS QUANTIDADE,
(INF.QUAN_INF * QTE1_PRO) AS QUANTIDADE_KG_L

FROM NFENTRA NF
 LEFT JOIN INFENTRA INF ON (NF.CODI_EMP = INF.CODI_EMP AND NF.CODI_TRA = INF.CODI_TRA AND NF.NUME_NFE = INF.NUME_NFE AND NF.SERI_NFE = INF.SERI_NFE)
 LEFT JOIN FUNCAOTOPER FT ON (NF.CODI_TOP = FT.CODI_TOP)
 LEFT JOIN PRODSERV P ON (INF.CODI_PSV = P.CODI_PSV)
 LEFT JOIN PRODUTO PD ON (P.CODI_PSV = PD.CODI_PSV)
WHERE FT.CODI_PTO = 1
AND PD.CODI_TRA IN (721, 10008422, 10006990, 10004184, 10005327)
AND NF.DREC_NFE BETWEEN TO_DATE('01/01/2019') AND CURRENT_DATE;