SELECT NF.CODI_EMP,
         TR.RAZA_TRA,
         p.nome_pes,
         EXTRACT(MONTH
FROM NF.DEMI_NOT) AS MES, EXTRACT(YEAR
FROM NF.DEMI_NOT) AS ANO, PD.DESC_PSV, SUM (case
    WHEN ( FT.FUNC_TOP = 'A' ) THEN
    INF.QTDE_INO * PR.QTE1_PRO
    ELSE INF.QTDE_INO * (-1) * PR.QTE1_PRO
    END )as QTDE_INO_KG_L , SUM (INF.VLOR_INO / PR.QTE1_PRO) AS VALOR_KG_L, SUM (CASE
    WHEN ( FT.FUNC_TOP = 'A' ) THEN
    (INF.VLOR_INO * QTDE_INO / PR.QTE1_PRO)
    WHEN ( FT.FUNC_TOP = 'S' ) THEN
    (-1 * INF.VLOR_INO * QTDE_INO / PR.QTE1_PRO)
    END ) AS VALOR_TOTAL_KG_L
FROM INOTA INF
INNER JOIN NOTA NF
    ON (NF.NPRE_NOT = INF.NPRE_NOT)
INNER JOIN TRANSAC TR
    ON (TR.CODI_TRA = NF.CODI_TRA)
INNER JOIN PRODSERV PD
    ON (PD.CODI_PSV = INF.CODI_PSV)
INNER JOIN FUNCAOTOPER FT
    ON (FT.CODI_TOP = NF.CODI_TOP
        AND FT.CODI_PTO = 102) left outer
JOIN TIPOOPER T
    ON (NF.CODI_TOP = T.CODI_TOP)
LEFT JOIN PRODUTO PR
    ON (PR.CODI_PSV = PD.CODI_PSV)
LEFT JOIN TRANSAC FAB
    ON (PR.CODI_TRA = FAB.CODI_TRA)
LEFT JOIN vendedorcli V
    ON (TR.CODI_TRA = V.CODI_TRA
        AND NF.CODI_EMP = V.CODI_EMP)
LEFT JOIN PESSOAL P
    ON (P.CODI_PES = v.cod1_pes)
WHERE (NF.SITU_NOT = '5')
        AND (NF.DEMI_NOT
    BETWEEN to_date('01/01/2019')
        AND to_date('29/11/2019'))
        AND FAB.CODI_TRA = 10006412
GROUP BY  ( NF.CODI_EMP, TR.RAZA_TRA, p.nome_pes, EXTRACT(MONTH
FROM NF.DEMI_NOT), EXTRACT(YEAR
FROM NF.DEMI_NOT), PD.DESC_PSV )
UNION
allSELECT NFE.CODI_EMP,
         TR.RAZA_TRA,
         p.nome_pes,
         EXTRACT(MONTH
FROM NFE.DREC_NFE), EXTRACT(YEAR
FROM NFE.DREC_NFE), PD.DESC_PSV, SUM (
    CASE
    WHEN ( FT.FUNC_TOP = 'A' ) THEN
    INFE.QUAN_INF * PR.QTE1_PRO
    ELSE INFE.QUAN_INF * (-1) * PR.QTE1_PRO
    END ) AS QTDE_INO_KG_L, SUM ( INFE.VLOR_INF / PR.QTE1_PRO), SUM (
    CASE
    WHEN coalesce(NFE.TOTA_NFE,0) > 0 THEN
    (-1 * INFE.VLOR_INF * (INFE.QUAN_INF) / PR.QTE1_PRO)
    ELSE 0
    END ) AS VALOR_TOTAL
FROM INFENTRA INFE
INNER JOIN NFENTRA NFE
    ON (NFE.NUME_NFE = INFE.NUME_NFE
        AND NFE.SERI_NFE = INFE.SERI_NFE
        AND NFE.CODI_EMP = INFE.CODI_EMP
        AND NFE.CODI_TRA = INFE.CODI_TRA)
INNER JOIN TRANSAC TR
    ON (TR.CODI_TRA = NFE.CODI_TRA)
LEFT JOIN CFO
    ON ( CFO.CCFO_CFO = NFE.CCFO_CFO )
INNER JOIN PRODSERV PD
    ON (PD.CODI_PSV = INFE.CODI_PSV)
INNER JOIN FUNCAOTOPER FT
    ON (FT.CODI_TOP = NFE.CODI_TOP
        AND FT.CODI_PTO = 102) left outer
JOIN TIPOOPER T
    ON (NFE.CODI_TOP = T.CODI_TOP)
LEFT JOIN PRODUTO PR
    ON (PR.CODI_PSV = PD.CODI_PSV)
LEFT JOIN TRANSAC FAB
    ON (PR.CODI_TRA = FAB.CODI_TRA)
LEFT JOIN vendedorcli V
    ON (TR.CODI_TRA = V.CODI_TRA
        AND NFE.CODI_EMP = V.CODI_EMP)
LEFT JOIN PESSOAL P
    ON (P.CODI_PES = v.cod1_pes)
WHERE (NFE.DREC_NFE
    BETWEEN to_date('01/01/2019')
        AND to_date('29/11/2019'))
        AND FAB.CODI_TRA = 10006412
GROUP BY  ( NFE.CODI_EMP, TR.RAZA_TRA, p.nome_pes, EXTRACT(MONTH
FROM NFE.DREC_NFE), EXTRACT(YEAR
FROM NFE.DREC_NFE), PD.DESC_PSV) 